import { useEffect, useState } from "react";
import { Download, RefreshCw, Save, Upload, Wifi } from "lucide-react";
import { attendanceApi, employeeApi, shiftAssignmentApi } from "../api/payroll";
import { getErrorMessage } from "../api/client";
import { Button } from "../components/ui/Button";
import { Card } from "../components/ui/Card";
import { Input } from "../components/ui/Input";
import { Select } from "../components/ui/Select";
import type { AttendanceMode, AttendanceSettings, Employee } from "../types";

const today = () => { const value = new Date(); return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; };
const currentTime = () => new Date().toTimeString().slice(0, 5);
export function AttendancePage() {
  const [settings, setSettings] = useState<AttendanceSettings>({ attendanceMode: "MANUAL", biometricEnabled: false });
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [employeeId, setEmployeeId] = useState(0); const [date, setDate] = useState(today()); const [clockIn, setClockIn] = useState(""); const [clockOut, setClockOut] = useState("");
  const [file, setFile] = useState<File>(); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { attendanceApi.getSettings().then(setSettings).catch(e => setError(getErrorMessage(e))); employeeApi.search({ status: "ACTIVE", page: 0, size: 1000 }).then(r => setEmployees(r.content)).catch(() => undefined); }, []);
  useEffect(() => { if (!employeeId || !date) return; setClockOut(""); shiftAssignmentApi.search({ employeeId, startDate: date, endDate: date }).then(rows => { if (rows[0]?.startTime) setClockIn(rows[0].startTime.slice(0, 5)); }).catch(() => undefined); }, [employeeId, date]);
  useEffect(() => { if (settings.attendanceMode === "PUNCHES" && settings.biometricEnabled) { const timer = window.setInterval(() => attendanceApi.list(date, date).catch(() => undefined), 10000); return () => window.clearInterval(timer); } }, [settings.attendanceMode, settings.biometricEnabled, date]);
  function clockOn() { if (!employeeId) return setError("Choose an employee first."); if (date > today()) return setError("Future attendance is not allowed."); if (!clockIn) setClockIn(currentTime()); setClockOut(""); setMessage("Clock on captured. You can now clock off."); }
  function clockOff() { if (!clockIn) return setError("Clock on is required before clock off."); setClockOut(currentTime()); setMessage("Clock off captured. You can edit the time before saving."); }
  async function saveManual() { if (!employeeId || !clockIn) return setError("Employee and clock-on are required."); if (date > today()) return setError("Future attendance is not allowed."); try { await attendanceApi.save({ employeeId, date, clockIn, clockOut: clockOut || undefined, source: "MANUAL" }); setMessage("Attendance saved."); } catch (e) { setError(getErrorMessage(e)); } }
  function downloadTemplate() { const csv = `Employee Code,Punch Date,Punch Time,Type\n${employees.map(e => `${e.employeeCode},,,`).join("\n")}`; const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const a = document.createElement("a"); a.href = url; a.download = "attendance-punch-template.csv"; a.click(); URL.revokeObjectURL(url); }
  async function uploadPunches() { if (!file) return setError("Choose a CSV file first."); const rows = (await file.text()).trim().split(/\r?\n/).slice(1); let count = 0; for (const row of rows) { const [code, punchDate, punchTime, type] = row.split(",").map(v => v.trim()); const employee = employees.find(e => e.employeeCode === code); if (employee && punchDate && punchTime) { const current = (await attendanceApi.list(punchDate, punchDate)).find(x => x.employeeId === employee.id); await attendanceApi.save({ employeeId: employee.id, date: punchDate, clockIn: type.toUpperCase() === "IN" ? punchTime : current?.clockIn, clockOut: type.toUpperCase() === "OUT" ? punchTime : current?.clockOut, source: "PUNCH" }); count++; } } setMessage(`${count} punch rows imported.`); }
  return <div className="space-y-6"><Card><p className="text-sm font-bold uppercase tracking-[0.18em] text-fern">Attendance</p><h2 className="mt-2 font-display text-3xl font-extrabold text-ink">Employee Attendance</h2><p className="mt-2 text-sm text-ink/60">Record manual attendance or import punch data based on your system configuration.</p></Card>
  {settings.attendanceMode === "MANUAL" ? <Card><h3 className="font-display text-xl font-extrabold">Manual attendance</h3><p className="mt-1 text-sm text-ink/60">Future dates and future times are blocked. Clock off is available only after clock on.</p><div className="mt-5 grid gap-4 md:grid-cols-4"><Select label="Employee" value={employeeId} onChange={e => setEmployeeId(Number(e.target.value))}><option value={0}>Choose employee</option>{employees.map(e => <option key={e.id} value={e.id}>{e.employeeCode} — {e.fullName}</option>)}</Select><Input label="Date" type="date" max={today()} value={date} onChange={e => setDate(e.target.value)} /><Input label="Clock on" type="time" value={clockIn} onChange={e => setClockIn(e.target.value)} /><Input label="Clock off" type="time" disabled={!clockIn} value={clockOut} onChange={e => setClockOut(e.target.value)} /></div><div className="mt-5 flex flex-wrap gap-3"><Button variant="secondary" onClick={clockOn}>Clock on</Button><Button variant="secondary" onClick={clockOff} disabled={!clockIn}>Clock off</Button><Button onClick={saveManual} disabled={!clockIn}><Save size={17} />Save attendance</Button></div></Card> : <Card><div className="flex items-center justify-between"><div><h3 className="font-display text-xl font-extrabold">Punch uploader</h3><p className="mt-1 text-sm text-ink/60">Employee Code, Punch Date, Punch Time, Type (IN/OUT).</p></div><Button variant="secondary" onClick={downloadTemplate}><Download size={17} />Download template</Button></div><div className="mt-6 flex flex-wrap items-end gap-4"><Input label="Upload CSV" type="file" accept=".csv" onChange={e => setFile(e.target.files?.[0])} /><Button onClick={uploadPunches}><Upload size={17} />Import punches</Button>{settings.biometricEnabled && <span className="flex items-center gap-2 rounded-2xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700"><Wifi size={17} />Sync active <RefreshCw size={15} /></span>}</div></Card>}{(error || message) && <p className={`rounded-2xl px-4 py-3 text-sm font-semibold ${error ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}>{error || message}</p>}</div>;
}
